name: build-check

on: push

jobs:
   build:
      runs-on: [ubuntu-latest]

      steps:
        - uses: actions/checkout@v3

      - name: banking-build-check
        shell: bash
        run: |
          pip install --user cpp-coveralls
          cmake -H. -B_build -DBUILD_TESTS=ON
          cmake --build _build
          cd _build
          ./check --enable-gcov
          cd ..
          coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
