name: build-check

on: push

jobs:
   build:
      runs-on: [ubuntu-latest]

      steps:
        - uses: actions/checkout@v3

        - name: banking-build-check
          shell: bash
          run: |
           git submodule update --init --recursive
           pip install --user cpp-coveralls
           sudo apt-get install -y lcov
           cmake -H. -B_build -DBUILD_TESTS=ON
           cmake --build _build
           cd _build
           ./check --enable-gcov
           cd ..
           lcov --capture --directory output/CMakeFiles/banking.dir/banking --output-file ./lcov.info
           lcov --remove ./lcov.info '/home/runner/work/tp-lab05/tp-lab05/third-party/gtest/*' -o ./lcov_filtered.info
           coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
        - name: coveralls
          uses: coverallsapp/github-action@master
          with:
            path-to-lcov: "./lcov_filtered.info"
            github-token: ${{ secrets.github_token }}
