name: build-check

on: push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v1
   - name: build
     run: |
      git submodule update --init --recursive
      cmake -B ./output
      cd output
      make
      cd ..
 tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: test
        shell: bash
        run: |
          git submodule update --init --recursive
          cmake -B ./output
          cd output
          make
      - name: install lcov
        run: |
          sudo pip install --user cpp-coveralls
          sudo apt-get install -y lcov
      - name: run lcov
        run: | 
          lcov --zerocounters --directory home/runner/work/lab05/lab05/output/CMakeFiles/banking.dir/banking
          lcov --capture --initial --directory home/runner/work/lab05/lab05/output/CMakeFiles/banking.dir/banking --output-file myOutputFile
          lcov --remove ./lcov.info '/home/runner/work/tp-lab05/tp-lab05/third-party/gtest/*' -o ./lcov_filtered.info
      - name: coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          path-to-lcov: "./lcov_filtered.info"
          github-token: ${{ secrets.github_token }}
